/*
 * Insert dataset version
 */
INSERT OR REPLACE INTO user (name, value) VALUES ('dsJapanVersion', '1.2.1');

INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Tokyo', 'Japan', 5000, 50, 1);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Kyoto', 'Japan', 3500, 35, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Yokohama', 'Japan', 2000, 20, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Osaka', 'Japan', 1000, 10, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Nagasaki', 'Japan', 500, 5, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Hakodate', 'Japan', 500, 5, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Fukuoka', 'Japan', 250, 1, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Kanazawa', 'Japan', 1500, 15, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Tashirojima', 'Japan', 0, 0, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Kiryu', 'Japan', 250, 3, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Hiroshima', 'Japan', 1500, 12, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Nagoya', 'Japan', 2000, 20, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Sapporo', 'Japan', 2500, 25, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Kobe', 'Japan', 1750, 15, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Kawasaki', 'Japan', 750, 5, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Saitama', 'Japan', 750, 5, 0);
INSERT OR IGNORE INTO cities (city, country, cityPrice, constructionsNeeded, isCapital) VALUES ('Uwajima', 'Japan', 25, 0, 0);

-- Insert constructions for Tokyo, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Akihabara Electric Town', '秋葉原電気街', 2000, 150, 'Akihabara is a major shopping area for electronic, computer, anime, and otaku goods, including new and used items.', 'akihabara.jpg', 'http://ja.wikipedia.org/wiki/%E7%A7%8B%E8%91%89%E5%8E%9F'
UNION SELECT 'Asahi Beer Hall', 'スーパードライホール', 990, 80, 'The Asahi Beer Hall (a.k.a. Super Dry Hall, or Flamme d''Or) is one of the buildings of the Asahi Breweries headquarters located on the east bank of the Sumida River. It was designed by French designer Philippe Starck and was completed in 1989. It is considered one of Tokyo''s most recognizable modern structures.', 'asahibeerhall.JPG', 'http://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%BC%E3%83%91%E3%83%BC%E3%83%89%E3%83%A9%E3%82%A4%E3%83%9B%E3%83%BC%E3%83%AB'
UNION SELECT 'Edo-Tokyo Museum', '江戸東京博物館', 1500, 100, 'The Edo-Tokyo Museum is a museum of the history of Tokyo.', 'edotokyomuseum.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B1%9F%E6%88%B8%E6%9D%B1%E4%BA%AC%E5%8D%9A%E7%89%A9%E9%A4%A8'
UNION SELECT 'Fuji TV', 'フジテレビ', 1000, 80, 'Fuji TV is a Japanese television station based in Daiba.', 'fujiterebi.jpg', 'http://ja.wikipedia.org/wiki/%E3%83%95%E3%82%B8%E3%83%86%E3%83%AC%E3%83%93%E3%82%B8%E3%83%A7%E3%83%B3'
UNION SELECT 'Harajuku Elvis Dancers', '原宿のエルヴィス', 25, 25, 'Every sunny Sunday in front of Yoyogi park.', 'elvisdancers.jpg', 'http://www.youtube.com/watch?v=UkuwqNuR2As'
UNION SELECT 'Hibiya Oktoberfest', '日比谷オクトーバーフェスト', 555, 55, 'Hibiya Oktoberfest is the Japanese version of the Munich Oktoberfest. It is held once a year in May in Hibiya Park.', 'hibiyaoktoberfest.JPG', 'http://www.oktoberfest.jp/'
UNION SELECT 'Icebar Tokyo', 'アイスバー東京', 350, 35, 'In the Icebar Tokyo you can experience the Arctic all year round.', 'icebartokyo.jpg', 'http://www.icebartokyo.com/'
UNION SELECT 'Kameido Tenjin Shrine', '亀戸天神社', 1030, 85, 'Kameido Shrine was built in 1662 and has one of Japan''s few remaining red drum bridges. It is famous for the Wisteria (Fuji) Festival, usually held in late April / early May.', 'kameidotenjinshrine.JPG', 'http://ja.wikipedia.org/wiki/%E4%BA%80%E6%88%B8%E5%A4%A9%E7%A5%9E%E7%A4%BE'
UNION SELECT 'Kanda Shrine', '神田明神', 1050, 80, 'Kanda Shrine is a Shinto shrine located in Chiyoda which dates back 1270 years.', 'kandamyojin.jpg', 'http://ja.wikipedia.org/wiki/%E7%A5%9E%E7%94%B0%E6%98%8E%E7%A5%9E'
UNION SELECT 'Kiyosumi Garden', '清澄庭園', 1140, 90, 'Kiyosumi Garden is a traditional Japanese stroll garden. It was constructed along classic principles in 1878-85, during the Meiji Period. By subtle hints in path construction and placement the visitor is led on a walk around the lake. Water-worn boulders were brought in from all over Japan, to give the garden its character.', 'kiyosumigarden.JPG', 'http://ja.wikipedia.org/wiki/%E6%B8%85%E6%BE%84%E5%BA%AD%E5%9C%92'
UNION SELECT 'Koishikawa Botanical Gardens', '小石川植物園', 1480, 130, 'Not to be confused with Koishikawa Kōrakuen Garden, Koishikawa Botanical Gardens (40 acres, 16 hectares) are botanical gardens with arboretum operated by the University of Tokyo Graduate School of Science. The gardens date to 1684, when the 5th Tokugawa shogun, Tsunayoshi, established the Koishikawa Medicinal Herb Garden.', 'koishikawabotanicalgardens.JPG', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E5%A4%A7%E5%AD%A6%E5%A4%A7%E5%AD%A6%E9%99%A2%E7%90%86%E5%AD%A6%E7%B3%BB%E7%A0%94%E7%A9%B6%E7%A7%91%E9%99%84%E5%B1%9E%E6%A4%8D%E7%89%A9%E5%9C%92'
UNION SELECT 'Kyu Shiba Rikyu Garden', '旧芝離宮恩賜庭園', 1000, 120, 'Kyu Shiba Rikyu Garden is one of two surviving Edo period clan gardens in modern Tokyo.', 'kyushibarikyuteien.jpg', 'http://ja.wikipedia.org/wiki/%E6%97%A7%E8%8A%9D%E9%9B%A2%E5%AE%AE%E6%81%A9%E8%B3%9C%E5%BA%AD%E5%9C%92'
UNION SELECT 'Life-size Gundam', 'ガンダム', 580, 50, 'A 1:1 real-size, scaled Gundam statue that was built in Shiokaze Park on Odaiba island.', 'odaibagundam.jpg', 'http://www.youtube.com/watch?v=eM6nUX57gCg'
UNION SELECT 'Meiji Shrine', '明治神宮', 1500, 200, 'Meiji Shrine a Shinto shrine which is dedicated to the deified spirits of Emperor Meiji and his wife, Empress Shōken.', 'meijijingu.jpg', 'http://ja.wikipedia.org/wiki/%E6%98%8E%E6%B2%BB%E7%A5%9E%E5%AE%AE'
UNION SELECT 'Midtown Tower', 'ミッドタウンタワー', 2000, 150, 'Midtown Tower is a mixed-use skyscraper located in Roppongi. Completed in 2007, at 248.1 meters it is currently the tallest office building in Tokyo.', 'midtowntower.jpg', 'http://ja.wikipedia.org/wiki/%E3%83%9F%E3%83%83%E3%83%89%E3%82%BF%E3%82%A6%E3%83%B3%E3%83%BB%E3%82%BF%E3%83%AF%E3%83%BC'
UNION SELECT 'Nezu Shrine', '根津神社', 1320, 95, 'Nezu Shrine is a Shinto shrine established in 1705. It is famous for its Azalea Festival (Tsutsuji Matsuri) which is held on its grounds from early April until early May.', 'nezushrine.JPG', 'http://ja.wikipedia.org/wiki/%E6%A0%B9%E6%B4%A5%E7%A5%9E%E7%A4%BE'
UNION SELECT 'Oldenburg Giant Saw', '巨大ノコギリ', 250, 40, 'A giant saw. Awesome!', 'tokyobigsaw.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E5%9B%BD%E9%9A%9B%E5%B1%95%E7%A4%BA%E5%A0%B4'
UNION SELECT 'Rainbow Bridge', 'レインボーブリッジ', 5000, 300, 'Rainbow bridge is a 798 metres long suspension bridge crossing northern Tokyo Bay between Shibaura Pier and the Odaiba waterfront development.', 'rainbowbridge.jpg', 'http://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%A4%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%96%E3%83%AA%E3%83%83%E3%82%B8'
UNION SELECT 'Rikugi-en', '六義園', 2000, 150, 'Rikugien is a Tokyo metropolitan park in Bunkyō-ku. The name Rikugi comes from the idea of the six elements in waka poetry (en means garden or park)', 'rikugien.jpg', 'http://ja.wikipedia.org/wiki/%E5%85%AD%E7%BE%A9%E5%9C%92'
UNION SELECT 'Ryōgoku Kokugikan', '両国国技館', 1250, 125, 'Ryōgoku Kokugikan, also known as Sumo Hall, is an indoor sporting arena located next to the Edo-Tokyo Museum. The current building was opened in 1985 and has a capacity of 13,000 people. It is mainly used for sumo wrestling tournaments', 'ryogokukokugikan.jpg', 'http://ja.wikipedia.org/wiki/%E4%B8%A1%E5%9B%BD%E5%9B%BD%E6%8A%80%E9%A4%A8'
UNION SELECT 'Sanja Matsuri', '三社祭', 1600, 65, 'Sanja Matsuri (lit. "Three Shrine Festival") is one of the three great Shinto festivals in Tokyo, along with the Kanda Matsuri and Sannō Matsuri. It is considered one of the wildest and largest. The festival is held in honor of Hinokuma Hamanari, Hinokuma Takenari and Hajino Nakatomo, the three men who established and founded Sensō-ji.', 'sanjamatsuri.jpg', 'http://ja.wikipedia.org/wiki/%E4%B8%89%E7%A4%BE%E7%A5%AD'
UNION SELECT 'Sega Joyopolis', 'セガジョイポリス', 1000, 85, 'Sega Joypolis is an indoor amusement park located in Odaiba.', 'segajoyopolis.jpg', 'http://sega.jp/joypolis/tokyo/home_e.shtml'
UNION SELECT 'Sengaku-ji', '泉岳寺', 750, 50, 'Sengakuji is a Sōtō Zen Buddhist temple. The graves of the Forty-seven Ronin are here.', 'sengakuji.jpg', 'http://ja.wikipedia.org/wiki/%E6%B3%89%E5%B2%B3%E5%AF%BA'
UNION SELECT 'Sensō-ji', '浅草寺', 1300, 90, 'Sensō-ji is an ancient Buddhist temple located in Asakusa. It is Tokyo''s oldest temple, and one of its most significant.', 'sensoji.jpg', 'http://ja.wikipedia.org/wiki/%E6%B5%85%E8%8D%89%E5%AF%BA'
UNION SELECT 'Shinjuku Gyoen National Garden', '新宿御苑', 1600, 140, 'Shinjuku Gyoen is a large park with an eminent garden in Shinjuku and Shibuya. It was originally a residence of the Naitō family (Daimyo) in the Edo period.', 'shinjukugyoen.jpg', 'http://ja.wikipedia.org/wiki/%E6%96%B0%E5%AE%BF%E5%BE%A1%E8%8B%91'
UNION SELECT 'Statue of Liberty', '自由の女神像', 650, 65, 'The French Statue of Liberty came to Odaiba for one year in commemoration of "The French year in Japan". Because of its popularity, in 2000, a replica of the French Statue of Liberty was erected at the same place.', 'statueofliberty.jpg', 'http://ja.wikipedia.org/wiki/%E8%87%AA%E7%94%B1%E3%81%AE%E5%A5%B3%E7%A5%9E%E5%83%8F'
UNION SELECT 'Sudo Park', '須藤公園', 575, 40, 'Sudo Park is a small, quiet park located in Bunkyo-ku.', 'sudopark.JPG', 'http://www.city.bunkyo.lg.jp/sosiki_busyo_kouen_annai_kuritukouen_kouen_sudou.html'
UNION SELECT 'Tennoji Temple', '天王寺', 750, 70, 'Tennoji is a temple of the Tendai sect. It was founded in 1274 and now lies next to the Yanaka Cemetery near Nippori Station.', 'tennojitemple.JPG', 'http://ja.wikipedia.org/wiki/%E5%A4%A9%E7%8E%8B%E5%AF%BA_%28%E5%8F%B0%E6%9D%B1%E5%8C%BA%29'
UNION SELECT 'Todoroki Valley', '等々力渓谷', 300, 50, 'Todoroki Valley is located in Steagaya-ku and has a walking trail through a wooded valley along the small river Yagiwa-gawa', 'todorokivalley.jpg', 'http://ja.wikipedia.org/wiki/%E8%B0%B7%E6%B2%A2%E5%B7%9D#.E7.AD.89.E3.80.85.E5.8A.9B.E6.B8.93.E8.B0.B7'
UNION SELECT 'Tokyo Big Sight', '東京国際展示場', 1200, 100, 'Tokyo Big Sight is one of the largest convention venues within the city, and its most iconic representation is the visually-distinctive Conference Tower.', 'tokyobigsight.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E5%9B%BD%E9%9A%9B%E5%B1%95%E7%A4%BA%E5%A0%B4'
UNION SELECT 'Tokyo Disneyland', '東京ディズニーランド', 3500, 220, 'Tokyo Disneyland is a 115 acre (465,000 m²) theme park, was the first Disney park to be built outside of the United roundss and opened on April 15, 1983', 'tokyodisneyland.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E3%83%87%E3%82%A3%E3%82%BA%E3%83%8B%E3%83%BC%E3%83%A9%E3%83%B3%E3%83%89'
UNION SELECT 'Tokyo Imperial Palace', '皇居', 10000, 500, 'Tokyo Imperial Palace is the main residence of the Emperor of Japan.', 'tokyoimperialpalace.jpg', 'http://ja.wikipedia.org/wiki/%E7%9A%87%E5%B1%85'
UNION SELECT 'Tokyo Metropolitan Government Building', '東京都庁舎', 8000, 400, 'The Tokyo Metropolitan Government Building, also referred to as Tokyo City Hall or Tochō for short, houses the headquarters of the Tokyo Metropolitan Government. It governs not only the 23 wards, but also the cities, towns and villages that make up Tokyo as a whole.', 'tocho.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%BA%81%E8%88%8E'
UNION SELECT 'Tokyo Sky Tree', '東京スカイツリー', 6340, 634, 'Tokyo Sky Tree is a broadcasting, restaurant, and observation tower in Sumida. It became the tallest structure in Japan in 2010 and reached its full height of 634.0 metres in March 2011, making it the tallest tower in the world and the second tallest structure in the world after Burj Khalifa.', 'tokyoskytree.JPG', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E3%82%B9%E3%82%AB%E3%82%A4%E3%83%84%E3%83%AA%E3%83%BC'
UNION SELECT 'Tokyo Tower', '東京タワー', 4500, 250, 'Tokyo Tower is a communications and observation tower located in Shiba Park. At 332.5 metres, it is the second tallest artificial structure in Japan.', 'tokyotower.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E4%BA%AC%E3%82%BF%E3%83%AF%E3%83%BC'
UNION SELECT 'Tsukiji Fish Market', '築地市場', 1400, 75, 'Tsukiji is the biggest wholesale fish and seafood market in the world and also one of the largest wholesale food markets of any kind.', 'tsukiji.jpg', 'http://ja.wikipedia.org/wiki/%E7%AF%89%E5%9C%B0%E5%B8%82%E5%A0%B4'
UNION SELECT 'Ueno Park', '上野恩賜公園', 1000, 125, 'Ueno Park is a spacious public park, which was established in 1873 on lands formerly belonging to the temple of Kan''ei-ji. Amongst the country''s first public parks, it was founded following the western example as part of the borrowing and assimilation of international practices that characterizes the early Meiji period.', 'uenokoen.jpg', 'http://ja.wikipedia.org/wiki/%E4%B8%8A%E9%87%8E%E6%81%A9%E8%B3%9C%E5%85%AC%E5%9C%92'
UNION SELECT 'Venus Fort', 'ヴィーナスフォート', 600, 40, 'Venus Fort is a shopping mall located on Odaiba.', 'venusfort.jpg', 'http://ja.wikipedia.org/wiki/%E3%83%B4%E3%82%A3%E3%83%BC%E3%83%8A%E3%82%B9%E3%83%95%E3%82%A9%E3%83%BC%E3%83%88'
UNION SELECT 'Yasukuni Shrine', '靖国神社', 1300, 150, 'Yasukuni Shrine is a Shinto shrine which is dedicated to the soldiers and others who died fighting on behalf of the Emperor of Japan', 'yasukunijinja.jpg', 'http://ja.wikipedia.org/wiki/%E9%9D%96%E5%9B%BD%E7%A5%9E%E7%A4%BE'
UNION SELECT 'Zōjō-ji', '増上寺', 1450, 110, 'Zōjō-ji is a Buddhist temple in the Shiba neighborhood of Minato. It is the Great Main Temple of the Chinzai sect of the Shingon school. The main image is of Amida Buddha. The founder of Zōjō-ji was Yūyo Shōsō.', 'zojo-ji.JPG', 'http://ja.wikipedia.org/wiki/%E5%A2%97%E4%B8%8A%E5%AF%BA'
),
(SELECT cityID FROM cities WHERE city = 'Tokyo' AND country = 'Japan');


-- Insert constructions for Kyoto, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Arashiyama Monkey Park', '嵐山モンキーパーク', 450, 40, 'Arashiyama Monkey Park is inhabited by a troop of over 170 Japanese macaque monkeys', 'arashiyamamonkeypark.jpg', 'http://www.kmpi.co.jp/'
UNION SELECT 'Fushimi Inari Taisha', '伏見稲荷大社', 1150, 120, 'Fushimi Inari Taisha is the head shrine of Inari. The shrine sits at the base of a mountain also named Inari, and includes trails up the mountain to many smaller shrines.', 'fushimiinari.jpg', 'http://ja.wikipedia.org/wiki/%E4%BC%8F%E8%A6%8B%E7%A8%B2%E8%8D%B7%E5%A4%A7%E7%A4%BE'
UNION SELECT 'Ginkaku-ji', '銀閣寺', 2000, 70, 'Ginkaku-ji, the "Temple of the Silver Pavilion", is a Zen temple and one of the constructions that represent the Higashiyama Culture.', 'ginkakuji.jpg', 'http://ja.wikipedia.org/wiki/%E6%85%88%E7%85%A7%E5%AF%BA'
UNION SELECT 'Kamigamo Shrine', '上賀茂神社', 800, 60, 'Kamigamo Shrine is an important Shinto sanctuary and one of the oldest Shinto shrines in Japan.', 'kamigamo.jpg', 'http://ja.wikipedia.org/wiki/%E8%B3%80%E8%8C%82%E5%88%A5%E9%9B%B7%E7%A5%9E%E7%A4%BE'
UNION SELECT 'Kinkaku-ji', '金閣寺', 4500, 180, 'Kinkaku-ji ("Temple of the Golden Pavilion"), is a Zen Buddhist temple whose garden complex is an excellent example of Muromachi period garden design.', 'kinkakuji.jpg', 'http://ja.wikipedia.org/wiki/%E9%B9%BF%E8%8B%91%E5%AF%BA'
UNION SELECT 'Kiyomizu-dera', '清水寺', 2500, 250, 'Kiyomizu-dera is an independent Buddhist temple which was founded in the early Heian period.', 'kiyomizudera.jpg', 'http://ja.wikipedia.org/wiki/%E6%B8%85%E6%B0%B4%E5%AF%BA'
UNION SELECT 'Kyoto Botanical Garden', '京都府立植物園', 800, 200, 'The Kyoto Botanical Garden (area: 240,000 m²) is a major botanical garden with conservatory located next to the Kamo River.', 'kyotobotanicalgarden.jpg', 'http://ja.wikipedia.org/wiki/%E4%BA%AC%E9%83%BD%E5%BA%9C%E7%AB%8B%E6%A4%8D%E7%89%A9%E5%9C%92'
UNION SELECT 'Nijō Castle', '二条城', 1800, 190, 'Nijō Castle is a flatland castle which consists of two concentric rings of fortifications, the Ninomaru Palace, the ruins of the Honmaru Palace, various support buildings and several gardens.', 'nijocastle.jpg', 'http://ja.wikipedia.org/wiki/%E4%BA%8C%E6%9D%A1%E5%9F%8E'
UNION SELECT 'Ryōan-ji', '龍安寺', 800, 150, 'Ryōan-ji ("The Temple of the Dragon at Peace") is a Zen temple whose garden is considered to be one of the finest examples of a Japanese rock garden in Japan.', 'ryoanji.jpg', 'http://ja.wikipedia.org/wiki/%E9%BE%8D%E5%AE%89%E5%AF%BA'
UNION SELECT 'Sanjūsangen-dō', '三十三間堂', 1200, 120, 'The name Sanjūsangen-dō literally means Hall with thirty three spaces between columns, describing the architecture of the long main hall of the temple.', 'sanjusangendo.jpg', 'http://ja.wikipedia.org/wiki/%E4%B8%89%E5%8D%81%E4%B8%89%E9%96%93%E5%A0%82'
UNION SELECT 'Tenryū-ji', '天龍寺', 1250, 80, 'Tenryū-ji is the head temple of the Tenryū branch of Rinzai Zen Buddhism', 'tenryuji.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%A9%E9%BE%8D%E5%AF%BA'
),
(SELECT cityID FROM cities WHERE city = 'Kyoto' AND country = 'Japan');


-- Insert constructions for Yokohama, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Sankei-en', '三溪園', 1400, 145, 'Sankei-en is a traditional Japanese-style garden, which opened in 1906.', 'sankeien.jpg', 'http://ja.wikipedia.org/wiki/%E4%B8%89%E6%B8%93%E5%9C%92'
UNION SELECT 'Yamashita Park', '山下公園', 450, 40, 'Yamashita Park is a public park about 100 meters wide and 750 meters long next to Yokohama waterfront.', 'yamashitakoen.jpg', 'http://ja.wikipedia.org/wiki/%E5%B1%B1%E4%B8%8B%E5%85%AC%E5%9C%92'
UNION SELECT 'Yokohama Landmark Tower', '横浜ランドマークタワー', 3500, 300, 'The Yokohama Landmark Tower is the tallest building and 3rd tallest structure in Japan, standing 296.3 m high.', 'landmarktower.jpg', 'http://ja.wikipedia.org/wiki/%E6%A8%AA%E6%B5%9C%E3%83%A9%E3%83%B3%E3%83%89%E3%83%9E%E3%83%BC%E3%82%AF%E3%82%BF%E3%83%AF%E3%83%BC'
UNION SELECT 'Yokohama Marine Tower', '横浜マリンタワー', 1250, 100, 'Yokohama Marine Tower is a 106 metre high lattice tower with an observation deck at a height of 100 metres.', 'yokohamamarinetower.jpg', 'http://ja.wikipedia.org/wiki/%E6%A8%AA%E6%B5%9C%E3%83%9E%E3%83%AA%E3%83%B3%E3%82%BF%E3%83%AF%E3%83%BC'
),
(SELECT cityID FROM cities WHERE city = 'Yokohama' AND country = 'Japan');


-- Insert constructions for Osaka, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Dōtonbori', '道頓堀', 1000, 150, 'Dōtonbori is one of the principal tourist destinations in Osaka. It is a single street, running alongside the Dōtonbori canal between the Dōtonboribashi Bridge and the Nipponbashi Bridge. A former pleasure district, Dōtonbori is famous for its historic theatres (all gone now), its shops and restaurants, and its many neon and mechanised signs.', 'dotonbori.jpg', 'http://ja.wikipedia.org/wiki/%E9%81%93%E9%A0%93%E5%A0%80'
UNION SELECT 'Glico Man', 'グリコランナー', 100, 25, 'Originally installed in 1935, the giant neon athlete on a blue track, crossing the finish line, is a symbol of Glico candy.', 'glicoman.jpg', 'http://ja.wikipedia.org/wiki/%E6%88%8E%E6%A9%8B#.E6.88.8E.E6.A9.8B.E4.BB.98.E8.BF.91.E3.81.AE.E3.83.A9.E3.83.B3.E3.83.89.E3.83.9E.E3.83.BC.E3.82.AF'
UNION SELECT 'Ōsaka Aquarium Kaiyūkan', '海遊館', 2000, 200, 'The Osaka Aquarium Kaiyukan is one of the largest public aquariums in the world. The walk-through aquarium displays marine life in several habitats comprising 27 tanks in 16 main exhibits with a total volume of 10,941 tons of water.', 'osakaaquarium.jpg', 'http://ja.wikipedia.org/wiki/%E6%B5%B7%E9%81%8A%E9%A4%A8'
UNION SELECT 'Ōsaka Castle', '大坂城', 3500, 350, 'Ōsaka Castle is one of Japan''s most famous castles, and played a major role in the unification of Japan during the sixteenth century of the Azuchi-Momoyama period.', 'osakajo.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%A7%E5%9D%82%E5%9F%8E'
UNION SELECT 'Ōsaka Castle Hall', '大阪城ホール', 800, 100, 'Osaka Castle Hall is a multi-purpose arena in the Kyōbashi area of Osaka. It opened in 1983 and can seat up to 16,000 people. Each year, 10,000 people come to the hall to participate in a performance of Beethoven''s Symphony No. 9.', 'osakacastlehall.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%A7%E9%98%AA%E5%9F%8E%E3%83%9B%E3%83%BC%E3%83%AB'
UNION SELECT 'Ōsaka Castle Park', '大阪城公園', 600, 300, 'Osaka Castle Park is a public urban park and historical site situated at Ōsaka Castle. It is the second largest park in the city.', 'osakacastlepark.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%A7%E9%98%AA%E5%9F%8E%E5%85%AC%E5%9C%92'
UNION SELECT 'Shinsaibashi', '心斎橋', 1000, 120, 'Shinsaibashi is a district in the Chūō-ku ward of Osaka and the city''s main shopping area. It centers around Shinsaibashi-suji, a covered shopping street.', 'shinsaibashi.jpg', 'http://ja.wikipedia.org/wiki/%E5%BF%83%E6%96%8E%E6%A9%8B'
UNION SELECT 'Umeda Sky Building', '梅田スカイビル', 2000, 170, 'The Umeda Sky Building is the twelfth-tallest building in Osaka and one of the city''s most recognizable landmarks. It consists of two 40-story towers that connect at their two uppermost stories, with bridges and an escalator crossing the wide atrium-like space in the center.', 'umedaskybuilding.jpg', 'http://ja.wikipedia.org/wiki/%E6%A2%85%E7%94%B0%E3%82%B9%E3%82%AB%E3%82%A4%E3%83%93%E3%83%AB'
),
(SELECT cityID FROM cities WHERE city = 'Osaka' AND country = 'Japan');


-- Insert constructions for Nagasaki, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Confucius Shrine', '孔子廟', 750, 75, 'Confucius Shrine is said to be the world''s only Confucian shrine built outside China by Chinese hands. Even today the land on which it stands is Chinese territory and the land rights controlled by the Chinese Embassy in Tokyo.', 'confucianshrine.jpg', 'http://ja.wikipedia.org/wiki/%E5%AD%94%E5%AD%90%E5%BB%9F'
UNION SELECT 'Dejima', '出島', 2850, 275, 'Dejima (literally "exit island") was a small fan-shaped artificial island built in the bay of Nagasaki in 1634. This island, which was formed by digging a canal through a small peninsula, remained as the single place of direct trade and exchange between Japan and the outside world during the Edo period.', 'dejima.jpg', 'http://ja.wikipedia.org/wiki/%E5%87%BA%E5%B3%B6'
UNION SELECT 'Glover Garden', 'グラバー園', 2000, 200, 'Glover Garden is a park built for Thomas Blake Glover, a Scottish entrepreneur who contributed to the modernization of Japan in shipbuilding, coal mining, and many other fields.', 'glovergarden.jpg', 'http://ja.wikipedia.org/wiki/%E3%82%B0%E3%83%A9%E3%83%90%E3%83%BC%E5%9C%92'
UNION SELECT 'Megane Bridge', '眼鏡橋', 450, 35, 'Meganebashi or Spectacles Bridge, over the Nakashima River was built in Nagasaki in 1634 by the Chinese monk Mozi of Kofukuji Temple. It is said to be the oldest stone arch bridge in Japan.', 'meganebashi.jpg', 'http://ja.wikipedia.org/wiki/%E7%9C%BC%E9%8F%A1%E6%A9%8B_%28%E9%95%B7%E5%B4%8E%E5%B8%82%29'
UNION SELECT 'Mount Inasa', '稲佐山', 1700, 300, 'Mount Inasa is a hill to the west of Nagasaki which rises to a height of 333 metres.', 'inasayama.jpg', 'http://ja.wikipedia.org/wiki/%E7%A8%B2%E4%BD%90%E5%B1%B1'
UNION SELECT 'Nagasaki Chinatown', '長崎新地中華街', 900, 90, 'Nagasaki Chinatown was home for many Chinese sailors and traders who trade goods with the Japanese from the 15th to 19th centuries. The Chinese Traders came to Nagasaki because it was the only "open port" to visit Japan at this time.', 'chinatown.jpg', 'http://ja.wikipedia.org/wiki/%E9%95%B7%E5%B4%8E%E6%96%B0%E5%9C%B0%E4%B8%AD%E8%8F%AF%E8%A1%97'
UNION SELECT 'Nagasaki Peace Park', '平和公園', 700, 100, 'Nagasaki Peace Park is a park commemorating the atomic bombing of the city on August 9, 1945 during World War II.', 'nagasakipeacepark.jpg', 'http://ja.wikipedia.org/wiki/%E5%B9%B3%E5%92%8C%E5%85%AC%E5%9C%92'
UNION SELECT 'Ōura Church', '大浦天主堂', 600, 80, 'Ōura Church is a Roman Catholic church built soon after the end of the Japanese government''s Seclusion Policy in 1853.', 'ourachurch.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%A7%E6%B5%A6%E5%A4%A9%E4%B8%BB%E5%A0%82'
UNION SELECT 'Sōfuku-ji', '崇福寺', 900, 120, 'Sōfuku-ji is an Ōbaku Zen temple that was built by the Chinese monk Chaonian in 1629 as the family temple of the Chinese from Fujian Province who settled in Nagasaki.', 'sofukuji.jpg', 'http://ja.wikipedia.org/wiki/%E5%B4%87%E7%A6%8F%E5%AF%BA_%28%E9%95%B7%E5%B4%8E%E5%B8%82%29'
),
(SELECT cityID FROM cities WHERE city = 'Nagasaki' AND country = 'Japan');


-- Insert constructions for Hakodate, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Goryōkaku', '五稜郭', 1800, 250, 'Goryōkaku is a star fort, which was the main fortress of the short-lived Republic of Ezo.', 'fortgoryokaku.jpg', 'http://ja.wikipedia.org/wiki/%E4%BA%94%E7%A8%9C%E9%83%AD'
UNION SELECT 'Goryōkaku Tower', '五稜郭タワー', 1100, 105, 'From the 90-meter viewing platform of Goryōkaku Tower you can get a striking view of the star-shaped Goryōkaku fort.', 'goryokakutower.jpg', 'http://ja.wikipedia.org/wiki/%E4%BA%94%E7%A8%9C%E9%83%AD%E3%82%BF%E3%83%AF%E3%83%BC'
UNION SELECT 'Hakodate Magistrate''s Office', '箱館奉行所', 750, 90, 'Hakodate Magistrate''s Office was the governmental hall of the Republic of Ezo', 'magistrateoffice.jpg', 'http://www.hakodate-bugyosho.jp/'
UNION SELECT 'Hakodate Morning Market', '函館朝市', 250, 35, 'Crammed into a couple of bayfront buildings, rows of vendors sell a variety of seafood, but the main attraction is the huge selection of Hokkaidō''s famous crabs. Open 5 AM (6 AM in the winter) until noon.', 'asaichi.jpg', 'http://ja.wikipedia.org/wiki/%E5%87%BD%E9%A4%A8%E6%9C%9D%E5%B8%82'
UNION SELECT 'Hakodate Streetcar Network', '箱館路面電車', 350, 60, 'Hakodate has a useful two-line streetcar network connected to the train station.', 'streetcar.jpg', 'http://ja.wikipedia.org/wiki/%E5%87%BD%E9%A4%A8%E5%B8%82%E4%BC%81%E6%A5%AD%E5%B1%80%E4%BA%A4%E9%80%9A%E9%83%A8'
UNION SELECT 'Kanemori Red Brick Warehouses', '金森赤レンガ倉庫', 600, 85, 'Kanemori Red Brick Warehouses, built at the end of the Meiji era, now house a variety of commercial facilities, as well as restaurants serving seafood.', 'redbrickwarehouses.jpg', 'http://ja.wikipedia.org/wiki/%E9%87%91%E6%A3%AE%E8%B5%A4%E3%83%AC%E3%83%B3%E3%82%AC%E5%80%89%E5%BA%AB'
UNION SELECT 'Old Hakodate Public Hall', '旧函館区公会堂', 450, 60, 'The Old Hakodate Public Hall is located in Motomachi, the former residential area of foreign traders.', 'oldpublichall.jpg', 'http://ja.wikipedia.org/wiki/%E6%97%A7%E5%87%BD%E9%A4%A8%E5%8C%BA%E5%85%AC%E4%BC%9A%E5%A0%82'
UNION SELECT 'Ōnuma Quasi-National Park', '大沼国定公園', 1200, 115, 'Ōnuma Quasi-National Park is a 90.83 km² quasi-national park 20 km north of Hakodate. The park encompasses the volcanic Hokkaidō Komagatake as well as the Ōnuma and Konuma ponds, which abut against the west slope of the mountain.', 'onumakoen.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%A7%E6%B2%BC%E5%9B%BD%E5%AE%9A%E5%85%AC%E5%9C%92'
UNION SELECT 'Yonokawa Onsen Foot Bath', '湯の川温泉足湯', 65, 20, 'A free onsen foot bath. Relaxing!', 'yunokawafootbath.jpg', 'http://505060.blog12.fc2.com/blog-entry-853.html'
),
(SELECT cityID FROM cities WHERE city = 'Hakodate' AND country = 'Japan');


-- Insert constructions for Fukuoka, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Canal City Hakata', 'キャナルシティ博多', 700, 80, 'Canal City Hakata is a large shopping and entertainment complex. Called the "city within the city", it boasts numerous attractions including shops, cafes, restaurants, a theater, game center, cinemas, two hotels, and a canal, which runs through the complex.', 'canalcity.jpg', 'http://ja.wikipedia.org/wiki/%E3%82%AD%E3%83%A3%E3%83%8A%E3%83%AB%E3%82%B7%E3%83%86%E3%82%A3%E5%8D%9A%E5%A4%9A'
UNION SELECT 'Dazaifu Tenman-gū', '太宰府天満宮', 1100, 160, 'Dazaifu Tenman-gū is a Shinto shrine in Dazaifu, Fukuoka Prefecture. It is built over the grave of Sugawara no Michizane and is one of the main shrines dedicated to Tenjin, the deified form of Michizane.', 'dazaifutenmangu.jpg', 'http://ja.wikipedia.org/wiki/%E5%A4%AA%E5%AE%B0%E5%BA%9C%E5%A4%A9%E6%BA%80%E5%AE%AE'
UNION SELECT 'Fukuoka Castle', '福岡城', 2250, 260, 'Fukuoka Castle is also known as Maizuru Castle (舞鶴城) or Seki Castle (石城). Completed in the early Edo period for tozama daimyo Kuroda Nagamasa, it has been decreed a historic site by the Japanese government.', 'fukuokacastle.jpg', 'http://ja.wikipedia.org/wiki/福岡城'
UNION SELECT 'Kōmyōzen-ji', '光明禅寺', 900, 140, 'Kōmyōzen-ji is a Zen temple in Dazaifu, Fukuoka Prefecture. It is celebrated for its karesansui garden, the only example in Kyushu.', 'komyozenji.jpg', 'http://ja.wikipedia.org/wiki/%E5%85%89%E6%98%8E%E7%A6%85%E5%AF%BA'
UNION SELECT 'Kyushu National Museum', '九州国立博物館', 2000, 200, 'The Kyushu National Museum opened on October 16, 2005 in Dazaifu near Fukuoka. It was the first new national museum in Japan in over 100 years, and the first to elevate the focus on history over art.', 'kyushunationalmuseum.jpg', 'http://ja.wikipedia.org/wiki/%E4%B9%9D%E5%B7%9E%E5%9B%BD%E7%AB%8B%E5%8D%9A%E7%89%A9%E9%A4%A8'
UNION SELECT 'Yatai', '屋台', 50, 20, 'Fukuoka is well-known within Japan for having many yatai, which are small, mobile food stalls typically selling ramen or other hot food.', 'yatai.jpg', 'http://ja.wikipedia.org/wiki/%E5%B1%8B%E5%8F%B0'
),
(SELECT cityID FROM cities WHERE city = 'Fukuoka' AND country = 'Japan');


-- Insert constructions for Kanazawa, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT '21st Century Museum of Contemporary Art', '金沢21世紀美術館', 1650, 115, 'The 21st Century Museum of Contemporary Art is a museum of contemporary art in Kanazawa. In October 2005, one year after its opening the Museum marked 1,570,000 visitors.', '21stcenturymuseumofcontemporaryart.jpg', 'http://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A221%E4%B8%96%E7%B4%80%E7%BE%8E%E8%A1%93%E9%A4%A8'
UNION SELECT 'Higashi Chaya District', 'ひがし茶屋街', 1000, 75, 'Kanazawa has three chaya (lit. teahouse) districts. Higashi Chaya District is the largest one with  the Shima Teahouse and Kaikaro Teahouse, which are open to the public. Other buildings along the central street are now used as cafes and shops.', 'higashichayadistrict.jpg', 'http://ja.wikipedia.org/wiki/%E6%9D%B1%E5%B1%B1%E3%81%B2%E3%81%8C%E3%81%97'
UNION SELECT 'Kanazawa Castle', '金沢城', 2550, 190, 'Kanazawa Castle is a large, well-restored castle in Kanazawa. It is located adjacent to the celebrated Kenroku-en Garden, which once formed the castle''s private outer garden.', 'kanazawacastle.jpg', 'http://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A2%E5%9F%8E'
UNION SELECT 'Kanazawa Station', '金沢駅', 1300, 100, 'Kanazawa Station is a JR West railway station located in the city of Kanazawa. It is the biggest station in Ishikawa Prefecture.', 'kanazawastation.jpg', 'http://ja.wikipedia.org/wiki/%E9%87%91%E6%B2%A2%E9%A7%85'
UNION SELECT 'Kenroku-en', '兼六園', 1800, 115, 'Kenroku-en (Six Attributes Garden) is an old private garden. Along with Kairaku-en and Koraku-en, Kenroku-en is one of the Three Great Gardens of Japan.
The garden is located outside the gates of Kanazawa Castle where it originally formed the outer garden, and covers 114,436.65 m².', 'kenroku-en.jpg', 'http://ja.wikipedia.org/wiki/%E5%85%BC%E5%85%AD%E5%9C%92'
UNION SELECT 'Myōryū-ji', '妙立寺', 700, 125, 'Myōryū-ji, commonly known as Ninja-dera ("Ninja Temple"), is a buddist temple belonging to Nichiren sect. Myōryū-ji was designed to circumvent the restrictions and serve as a disguised military outpost. It was supplemented with considerable defences and escape routes, so that its defenders could alert the castle in the event of an attack. The temple''s defences aimed to guard against intruders or attack, and include hidden tunnels, secret rooms, traps, and a labyrinth of corridors and staircases.', 'myoryu-ji.jpg', 'http://ja.wikipedia.org/wiki/%E5%A6%99%E7%AB%8B%E5%AF%BA'
UNION SELECT 'Nagamachi', '長町武家屋敷跡', 900, 70, 'Nagamachi was a samurai district, where samurai and their families used to live. Though the Nagamachi area is promoted in the tourist brochures as the ‘samurai area’, in fact the overwhelming majority of the houses there today are not samurai houses, but modern post-war housing.', 'nagamachi.jpg', 'http://ja.wikipedia.org/wiki/%E9%95%B7%E7%94%BA%E6%AD%A6%E5%AE%B6%E5%B1%8B%E6%95%B7%E8%B7%A1'
UNION SELECT 'Oyama Shrine', '尾山神社', 800, 70, 'Oyama-jinja is a Shinto shrine, which was established in 1599 in Utatsuyama and was moved to its present location in 1873. The main gate was constructed in 1875. This gate is a peculiar mix of traditional Japanese, Chinese, and European religious architectural elements.', 'oyamashrine.jpg', 'http://ja.wikipedia.org/wiki/%E5%B0%BE%E5%B1%B1%E7%A5%9E%E7%A4%BE'
),
(SELECT cityID FROM cities WHERE city = 'Kanazawa' AND country = 'Japan');


-- Insert constructions for Tashirojima, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Cat Houses', '猫型ロッジ', 450, 55, 'Cat-themed houses designed by by mangaka Shotaro Ishinomori were built in order to attract more people to Tashirojima.
(Image source: www.tofugu.com)', 'cathouses.jpg', 'http://www.sanriku-kahoku.com/news/2010_03/i/091306i-neko.html'
UNION SELECT 'Cat Shrine', '猫神社', 75, 25, 'A shrine built to commemorate a cat which was killed by a fallen rock. 

(image source: http://www.tofugu.com)', 'catshrine.jpg', 'http://ja.wikipedia.org/wiki/%E7%94%B0%E4%BB%A3%E5%B3%B6#.E7.8C.AB.E7.A5.9E.E7.A4.BE'
),
(SELECT cityID FROM cities WHERE city = 'Tashirojima' AND country = 'Japan');


-- Insert constructions for Kiryu, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Caribbean Beach', 'カリビアンビーチ', 950, 80, 'The Caribbean Beach is an indoor heated water amusement park. It is constructed with a tropical island motif, making for a year-round warm amusement center for local citizens.
In the center of the facility, waves regularly roll in and out just like the ocean. There is also a giant water slide and "Rodeo Mountain" - a thrilling water ride which all children love. ', 'caribbeanbeach.jpg', 'http://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%AA%E3%83%93%E3%82%A2%E3%83%B3%E3%83%93%E3%83%BC%E3%83%81'
UNION SELECT 'Gunma Insect World', 'ぐんま昆虫の森', 830, 140, 'Located on the south face of Mt. Akagi, the park is located on a 48 hectare expanse of land known locally as the Fujiyama district of Niisatocho in Kiryu. Throught the park visitors can see serrated and sawtooth leaf oaks, fields, mulberry bushes, and other sorts of wild vegetation reminiscent of the Japanese countryside. Visitors can see the exhibits in the center as well as enjoy searching for insects in the wild. A variety of programs are planned throughout the year for all ages.', 'gunmainsectworld.jpg', 'http://ja.wikipedia.org/wiki/%E3%81%90%E3%82%93%E3%81%BE%E6%98%86%E8%99%AB%E3%81%AE%E6%A3%AE'
UNION SELECT 'Kiryū ga Oka Amusement Park', '桐生が岡遊園地', 1050, 135, 'The Kiryu ga Oka Amusement Park is located on the northwest side of Kiryu on the slope of Azuma mountain, next to the Kiryu ga Oka Zoo. The park is well known in the Kanto area because there is no entrance fee.
There are many rides and amusements in the park including a carousel, ferris wheel, Pirate''s Ship and cycle monorail.', 'kiryugaokaamusementpark.jpg', 'http://www.kiea.jp/AmusementPark.html'
UNION SELECT 'Kiryū ga Oka Zoo', '桐生が岡公園', 1600, 115, 'The zoo is located on a hill overlooking the city of Kiryu. The zoo was first opened in 1916. It emcompasses about a 6.1 hectare area. In the zoo there are lions, an elephant, giraffes, zebras, flamingoes, penguins, monkeys, a variety of snakes and a large aquarium along with a whole host of other domestic and exotic animals.
The park is particularly beautiful when the cherry trees and azaleas are in bloom in the springtime. Entrance to the zoo is free of charge. ', 'kiryuugaokazoo.jpg', 'http://ja.wikipedia.org/wiki/%E6%A1%90%E7%94%9F%E3%81%8C%E5%B2%A1%E5%85%AC%E5%9C%92'
UNION SELECT 'Kiryū Nature Sanctuary', '桐生自然観察の森', 750, 65, '　The 2.28 hectare mountain forest surrounding the temple became the prefecture''s Souzen Temple Nature Sanctuary in 1978. In the temple grounds are some of Kiryuu''s natural monuments - Japanese cypress, red pine, etc. - and on the back mountain, a deciduous forest consisting nostly of oak trees grows amidst low striped bamboo.', 'kiryunaturesanctuary.jpg', 'http://www.kiryu.co.jp/machikado/nature/shizen.html'
UNION SELECT 'Okawa Museum of Art', '大川美術館', 1200, 95, 'The Okawa Museum of Art is an art gallery that concentrates on modern Japanese art. The gallery, which opened in April 1989, presents the collection of the businessman and writer Eiji Ōkawa (大川栄ニ, 1924–2008), who was born in Kiryū, and has about 6500 items. At its core are about eighty works by Shunsuke Matsumoto and Hideo Noda; there are many works by other artists associated with these two. The gallery also has a hundred sketches by Takeji Fujishima and two hundred drawings by Toshi Shimizu.', 'okawamuseumofart.jpg', 'http://www.kiryu.co.jp/ohkawamuseum/default.htm'
UNION SELECT 'Tenmangu Shrine', '桐生天満宮', 1000, 80, 'About 1800 years ago, during the reign of Emperor Keiko, Jomo no Kunizukuri dedicated a shrine to Tenpo Nichimei, a descendent of Toshibe, on Isobe Hill. The establishemnt here of a shrine in honor of Isobe Myojin is the foundation of the present shrine.
Many centuries after that, from the year 1187, the Kiryu clan dynasty revered this god as their protector. In the year 1600, silk banners woven in Kiryu to be carried into the great battle at Sekigahara were first offered to the gods at Kiryu Tenmangu where a ceremony beseeching the gods for victory was held. This was the decisive battle in which Lord Tokugawa emerged victorious and assumed for himself the shogunate. ', 'tenmangushrine.jpg', 'http://ja.wikipedia.org/wiki/%E6%A1%90%E7%94%9F%E5%A4%A9%E6%BA%80%E5%AE%AE'
),
(SELECT cityID FROM cities WHERE city = 'Kiryu' AND country = 'Japan');


-- Insert constructions for Hiroshima, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Hiroshima Castle', '広島城', 3000, 235, 'Hiroshima Castle, sometimes called Carp Castle (鯉城) is a castle in Hiroshima, Japan which was the home of the daimyō (feudal lord) of the Hiroshima han (fief). Originally constructed in the 1590s, the castle was destroyed in the atomic bombing in 1945. It was rebuilt in 1958, a replica of the original which now serves as a museum of Hiroshima''s history prior to World War II.', 'hiroshimacastle.jpg', 'http://ja.wikipedia.org/wiki/広島城'
UNION SELECT 'Hiroshima Peace Memorial', '原爆ドーム', 1500, 160, 'Hiroshima Peace Memorial, commonly called the Atomic Bomb Dome or A-Bomb Dome, in Hiroshima, Japan, is part of the Hiroshima Peace Memorial Park and was designated a UNESCO World Heritage Site in 1996. The ruin serves as a memorial to the people who were killed in the atomic bombing of Hiroshima on August 6, 1945. Over 70,000 people were killed instantly, and another 70,000 suffered fatal injuries from the radiation.', 'hiroshimapeacememorial.JPG', 'http://ja.wikipedia.org/wiki/原爆ドーム'
),
(SELECT cityID FROM cities WHERE city = 'Hiroshima' AND country = 'Japan');


-- Insert constructions for Nagoya, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Higashiyama Zoo and Botanical Gardens', '東山動植物園', 1540, 200, 'The Higashiyama Zoo and Botanical Gardens is a zoo with botanical gardens.
Established in 1937, the Higashiyama Zoo is one of Asia''s largest, containing attractions such as botanical gardens and an amusement park. Its collection contains more than 125 species of mammals, including bears, elephants, giraffes, koalas, lions, and tigers; numerous reptiles and birds; and medaka tropical fish that flew on the space shuttle with one of Japan''s astronauts.', 'higashiyamazooandbotanicalgardens.jpg', 'http://ja.wikipedia.org/wiki/東山動植物園'
UNION SELECT 'Nagoya Castle', '名古屋城', 3500, 310, 'Nagoya Castle is a Japanese castle located in Nagoya, central Japan. During the Edo period, Nagoya Castle was the center of one of the most important castle towns in Japan—Nagoya-juku and it included the most important stops along the Minoji, which linked the Tōkaidō with the Nakasendō', 'nagoyacastle.jpg', 'http://ja.wikipedia.org/wiki/名古屋城'
UNION SELECT 'Nagoya TV Tower', '名古屋テレビ塔', 1160, 140, 'It is the oldest TV tower in Japan, and was completed in 1954. It is located in the centre of Hisaya Ōdori Park. The tower is 180 metres high, and has two main observation decks at the heights of 90 metres (the indoor Sky Deck) and 100 metres (the outdoor Sky Balcony). The tower also includes a restaurant and gallery at 30 metres. Nagoya TV Tower closely resembles the Eiffel Tower.', 'nagoyatvtower.JPG', 'http://ja.wikipedia.org/wiki/名古屋テレビ塔'
),
(SELECT cityID FROM cities WHERE city = 'Nagoya' AND country = 'Japan');


-- Insert constructions for Sapporo, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT '100th anniversary Memorial Park', '百年記念塔', 870, 75, 'This is the site of a giant (and somewhat imposing) tower which can be climbed, providing a good vantage point of Sapporo (though quite some distance from the city center) and surrounding mountains.', '100thanniversarymemorialpark.jpg', 'http://ja.wikipedia.org/wiki/%E5%8C%97%E6%B5%B7%E9%81%93%E7%99%BE%E5%B9%B4%E8%A8%98%E5%BF%B5%E5%A1%94'
UNION SELECT 'Asahiyama Memorial Park', '旭山記念公園', 1050, 110, 'A beautiful flower garden and natural park that overlooks the city center.', 'asahiyamapark.jpg', 'http://ja.wikipedia.org/wiki/%E6%97%AD%E5%B1%B1%E8%A8%98%E5%BF%B5%E5%85%AC%E5%9C%92'
UNION SELECT 'Former Hokkaidō Government Office', '北海道庁旧本庁舎', 700, 90, 'The Former Hokkaidō Government Office is an American-neo-baroque structure constructed in 1888 as a base of the Hokkaidō administration. The nickname is Akarenga or "Red Brick." It is the symbol of Hokkaidō and was designated a Japanese Important Cultural Property in 1969.', 'formerhokkaidogovernmentoffice.jpg', 'http://ja.wikipedia.org/wiki/北海道庁旧本庁舎'
UNION SELECT 'Historical Village of Hokkaido', '北海道開拓の村', 980, 95, 'A large historical village on the outskirts of Sapporo, offers a snapshot of Japan in the newly-industrialised age. The front gate (an old railway station) opens up into a series of opens alleys and buildings of the style pre-20th century. Also a variety of different gardens and shrines can be found here.', 'historicalvillageofhokkaido.jpeg', 'http://www.kaitaku.or.jp/info/info.htm'
UNION SELECT 'Hokkaido Museum of Modern Art', '北海道立近代美術館', 770, 50, 'Located in a small park, this modern art museum offers a collection that includes both Japanese and Western art, as well as as temporary exhibits.', 'hokkaidomuseumofmodernart.jpeg', 'http://www.aurora-net.or.jp/art/dokinbi/'
UNION SELECT 'Hokkaido University Botanic Garden', '北海道大学植物園', 920, 140, 'A large botanical garden. There are two rock gardens, a rose garden, a lilac display, a greenhouse, and various other gardens. There''s a small museum in the garden with artifacts from Hokkaido, some dating back to the Meiji period.', 'hokkaidouniversitybotanicgarden.JPG', 'https://ja.wikipedia.org/wiki/北海道大学北方生物圏フィールド科学センター耕地圏ステーション植物園'
UNION SELECT 'Ishiya Chocolate Factory', '白い恋人パーク', 810, 60, 'The chocolate factory has an incredibly corny, but fun, tour building up to a view of the actual chocolate making floor, and ending with a random toy museum. Famous for its white chocolate, which is sold under the brand "White Lovers" (白い恋人 shiroi koibito), and is only available in Hokkaido.', 'ishiyachocolatefactory.jpg', 'http://www.shiroikoibitopark.jp/'
UNION SELECT 'Moerenuma Park', 'モエレ沼公園', 480, 70, 'A popular excursion for Japanese families, this park offers several acres of carefully manicured grass and monumental landscape installations. Highlights include a 5-story glass pyramid and a man-made mountain, from which one can see all of Sapporo.', 'moerenumapark.jpg', 'https://ja.wikipedia.org/wiki/モエレ沼公園'
UNION SELECT 'Moiwayama', '藻岩山', 950, 100, 'This mountain, also called Moiwa Mountain, overlooks the city and is especially worthwhile at night to observe the city lights.', 'moiwayama.jpg', 'http://ja.wikipedia.org/wiki/藻岩山'
UNION SELECT 'Odori Park', '大通公園', 490, 100, 'Odori Park is a park located in the heart of Sapporo. Odori (大通) means "large street" in Japanese. Odori Park spans about 1.5 km and covers 78,901 m². During the urban planning of Sapporo, it was originally designated as the main street but it eventually became a park. Throughout the year, many events and ceremonies such as the Sapporo Lilac Festival and the Sapporo Snow Festival are held in the park, and local landmarks including the Sapporo TV Tower and the Sapporo City Archive Museum are located within its boundaries.', 'odoripark.jpg', 'http://ja.wikipedia.org/wiki/大通公園'
UNION SELECT 'Sapporo Art Park', '札幌芸術の森', 860, 65, 'Containing over 74 modern and contemporary sculptures, this art park makes for a great day trip.', 'sapporoartpark.jpg', 'http://www.artpark.or.jp/'
UNION SELECT 'Sapporo Beer Museum', 'サッポロビール博物館', 880, 80, 'The Sapporo Beer Museum is a museum located in the Sapporo Garden Park. Registered as one of the Hokkaidō Heritage sites in 2004, the museum is the only beer museum in Japan. The red-brick building was erected originally as a factory of the Sapporo Sugar Company in 1890, and later opened as a museum in July 1987. The building also houses the Sapporo Beer Garden in the south wing.', 'sapporobeermuseum.JPG', 'http://ja.wikipedia.org/wiki/サッポロビール博物館'
UNION SELECT 'Sapporo Clock Tower', '札幌市時計台', 850, 95, 'Sapporo Clock Tower is a wooden structure and well-known local tourist attraction.
The building is of American design and is one of the few surviving Western-style buildings in Sapporo, a city developed in the 1870s with assistance from the American government. It is known by many as the symbol of the city and is a main feature of almost all domestic and international tours of Sapporo. The clock after which it is named continues to run and keep time, and the chimes can be heard every hour.', 'sapporoclocktower.jpg', 'http://ja.wikipedia.org/wiki/札幌市時計台'
UNION SELECT 'Sapporo TV Tower', 'さっぽろテレビ塔', 1420, 135, 'The Sapporo TV Tower, built in 1957, is a 147.2 metre high TV Tower with an observation deck at a height of 90.38 metres. Located on the ground of Odori Park, the tower is open to tourists. Tourists can take panoramic pictures of Sapporo and Odori Park.', 'sapporotvtower.jpg', 'http://ja.wikipedia.org/wiki/さっぽろテレビ塔'
UNION SELECT 'Susukino', 'すすきの', 550, 115, 'Susukino is a red-light district and one of the major red-light districts in Japan along with Kabukichō, Tokyo, and Nakasu, Fukuoka. Currently, the district is congested with many restaurants, bars, hotels, and adult-entertainment establishments. Susukino is often noted as "薄野" in kanji, and "ススキノ" in katakana, and directly translated as "zebra grass field".', 'susukino.jpg', 'http://ja.wikipedia.org/wiki/すすきの'
),
(SELECT cityID FROM cities WHERE city = 'Sapporo' AND country = 'Japan');


-- Insert constructions for Kobe, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Akashi Kaikyō Bridge', '明石海峡大橋', 3740, 420, 'The Akashi-Kaikyō Bridge, also known as the Pearl Bridge, has the longest central span of any suspension bridge, at 1,991 metres. It was completed in 1998. The bridge links the city of Kobe on the mainland of Honshu to Iwaya on Awaji Island by crossing the busy Akashi Strait. It carries part of the Honshu-Shikoku Highway.', 'akashikaikyobridge.JPG', 'https://ja.wikipedia.org/wiki/明石海峡大橋'
UNION SELECT 'Ikuta Shrine', '生田神社', 1050, 90, 'Ikuta Shrine is a Shinto shrine in the Chūō Ward of Kobe, and is possibly among the oldest shrines in the country.', 'ikutashrine.jpg', 'https://ja.wikipedia.org/wiki/生田神社'
UNION SELECT 'Kikuseidai', '掬星台', 870, 60, 'Kikuseidai is a view point and a park just aside of the top of Maya-san in Kobe. It has one of three major Night Views of Japan and is called ten million dollar night view.', 'kikuseidai.jpg', 'https://ja.wikipedia.org/wiki/掬星台'
UNION SELECT 'Kitano-chō', '北野町', 1670, 125, 'Kitano-chō or Kitano Ijinkan is a historical district in Kobe, Japan, which contains a number of foreign residences from the late Meiji and early Taishō eras of Japanese history. While the term ijinkan (異人館) can refer to any foreign residence of this period in Japan, it usually refers to those of Kitano given the number and high concentration of those that remain. While some of the houses still serve as residences, many are open to tourists, making Kitano-chō one of the principal tourist attractions in Kobe.', 'kitano-cho.jpg', 'https://ja.wikipedia.org/wiki/北野町_(神戸市)'
UNION SELECT 'Kobe Chinatown', '南京町', 1450, 175, 'Kobe Chinatown in Kobe, Japan is one of only three designated Chinatowns in Japan. The area has over a hundred Chinese restaurants, shops, and a Chinese temple. Unlike its counterparts in Yokohama and Nagasaki, Kobe''s Nankinmachi sets itself apart as being the most colorful and foreign-looking Chinatown in all of Japan.', 'kobechinatown.JPG', 'https://ja.wikipedia.org/wiki/南京町_(神戸)'
UNION SELECT 'Kobe City Museum', '神戸市立博物館', 1800, 117, 'Kobe City Museum opened in 1982, and combines two previous collections, the Municipal Archaeological Art Museum and Municipal Namban Art Museum. The museum is housed in a neoclassical building of 1935, the former Kobe branch of the Bank of Tokyo. The collection of nearly thirty-nine thousand items comprises archaeological artefacts, works of art, old maps, and historical documents and artefacts relating to Kobe. It includes an important collection of Namban art, as well as a set of dōtaku and other items of the Yayoi period from excavations at Sakuragaoka that have been designated a National Treasure.', 'kobecitymuseum.jpg', 'https://ja.wikipedia.org/wiki/神戸市立博物館'
UNION SELECT 'Kobe City Museum of Literature', '神戸文学館', 1000, 70, 'Kobe City Museum of Literature is dedicated to the literary scene in the Meiji, Taishō, Shōwa, and Heisei periods. The museum opened in 2006 in the former Branch Memorial Chapel of Kwansei Gakuin University, a Meiji period building.', 'kobecitymuseumofliterature.jpg', 'https://ja.wikipedia.org/wiki/神戸文学館'
UNION SELECT 'Kobe Golf Club', '神戸ゴルフ倶楽部', 750, 139, 'The Kobe Golf Club is Japan''s first golf course, built on Mount Rokko in 1903 by English expatriate Arthur Hasketh Groom. The club began as a nine-hole course in 1903, but quickly expanded to eighteen the following year. Kobe Golf Club now boasts two full eighteen-hole courses, Maya and Suma, both sharing names of nearby regions. As the course was literally carved out of a mountain, it can be quite demanding and clubs are carried in canvas bags to reduce the strain on caddies.', 'kobegolfclub.jpg', 'https://ja.wikipedia.org/wiki/神戸ゴルフ倶楽部'
UNION SELECT 'Kobe Mosque', '神戸モスク', 1150, 145, 'Kobe Mosque, also known as Kobe Muslim Mosque, was founded in October, 1935 and is Japan''s first mosque. Its construction was funded by donations collected by the Islamic Committee of Kobe from 1928 until its opening in 1935. The mosque was confiscated by the Imperial Japanese Navy in 1943. However, it continues to function as mosque today. Owing to its basement and structure, the mosque was able to endure through the Great Hanshin earthquake.', 'kobemosque.jpg', 'https://ja.wikipedia.org/wiki/神戸モスク'
UNION SELECT 'Kobe Port Tower', '神戸ポートタワー', 1390, 175, 'Kobe Port Tower, a hyperboloid structure, is a 108 meter high lattice tower. It has an observation deck at a height of 90.28 metres. The red steel Port Tower offers a spectacular sight of the bay area and the surrounding area. The construction of the Kobe Port Tower was completed in 1963 and it looks like the Sydney Tower. The unusual design with scaffolding cover at the top is liked by tourists all over the world. The massive tower decorated with lights all over presents a unique sight at night.', 'kobeporttower.jpg', 'https://ja.wikipedia.org/wiki/神戸ポートタワー'
UNION SELECT 'Mount Maya', '摩耶山', 1270, 160, 'Mount Maya is a 698.6 m high mountain in Kobe. This mountain is one of the major peaks of the Rokkō Mountains, and is the most popular peak for visitors on the West-Rokkō Mountains.', 'mountmaya.jpg', 'https://ja.wikipedia.org/wiki/摩耶山'
UNION SELECT 'Port of Kobe', '神戸港', 1100, 142, 'The Port of Kobe is a Japanese maritime port in Kobe. Located at a foothill of the range of Mount Rokkō, flat lands are limited and constructions of artificial islands have carried out, to make Port Island, Rokko Island, island of Kobe Airport to name some.', 'portofkobe.JPG', 'https://ja.wikipedia.org/wiki/神戸港'
),
(SELECT cityID FROM cities WHERE city = 'Kobe' AND country = 'Japan');


-- Insert constructions for Kawasaki, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Kawasaki Daishi', '平間寺', 1220, 95, 'A large temple dedicated to famed monk and scholar Kobo Daishi. Featuring a 8-sided, 5-storied pagoda and more large temple buildings than you can shake a stick at, Kawasaki Daishi is a textbook example of a Japanese temple and remarkable primarily for the fact that on a weekday you can pretty much have the place to yourself.', 'kawasakidaishi.jpg', 'https://ja.wikipedia.org/wiki/平間寺'
UNION SELECT 'Nihon Minka-en', '日本民家園', 1410, 165, 'The large grounds display over twenty traditional Japanese houses (and the gate of Nagoya castle), dating from the late 17th to early 20th century and transplanted from around the country.', 'nihonminka-en.jpg', 'https://ja.wikipedia.org/wiki/日本民家園'
UNION SELECT 'Wakamiya Hachiman-gū Shrine', '若宮八幡宮', 695, 55, 'A quiet Shinto shrine that would be indistinguishable from your average neighborhood shrine if not for one thing: this happens to be one of Japan''s few remaining fertility shrines, and the deity venerated here assumes the form of a meter-long iron phallus, known as Kanamara-sama (金まら様, lit. "Iron Big Penis Lord").', 'wakamiyahachiman-gushrine.jpg', 'http://tomuraya.co.jp/wakamiya.htm'
),
(SELECT cityID FROM cities WHERE city = 'Kawasaki' AND country = 'Japan');


-- Insert constructions for Saitama, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Akigase Park', '秋ヶ瀬公園', 740, 55, 'Akigase Park occupies a section of flood plain of the Arakawa River, which is located at the western edge of Saitama City. The park covers an area of 100.1ha on the eastern side of the river. In 1971, former Urawa City established the park as a measure to manage the rising issue of insufficient park availability stemmed from rapid urban expansion. Baseball fields, soccer fields, and tennis courts, along with patches of pristine forest make up its grounds.', 'akigasepark.JPG', 'https://ja.wikipedia.org/wiki/秋ヶ瀬公園'
UNION SELECT 'Hikawa jinja', '氷川神社', 620, 78, 'Hikawa jinja is a major Shinto shrine in the Omiya district of Saitama. Surrounding the shrine is a large park in which there are many cherry blossom trees, a zoo and a museum. Omiya itself, literally ''Great Shrine'', derives from the special favor shown by Emperor Meiji, who raised Hikawa above all other shrines in the Kantō region. Standing behind three torii gates in a wood with many ancient Japanese elms, it claims to have a 2400-year history', 'hikawajinja.jpg', 'https://ja.wikipedia.org/wiki/氷川神社'
UNION SELECT 'John Lennon Museum', 'ジョン・レノン・ミュージアム', 450, 60, 'John Lennon Museum was a museum located inside the Saitama Super Arena. It was established to preserve knowledge of John Lennon''s life and musical career. It displayed Lennon''s widow Yoko Ono''s collection of his memorabilia as well as other displays. The museum opened on October 9, 2000, the 60th anniversary of Lennon’s birth, and closed on September 30, 2010, when its exhibit contract with Yoko Ono expired.', 'johnlennonmuseum.jpg', 'https://ja.wikipedia.org/wiki/ジョン・レノン・ミュージアム'
UNION SELECT 'Minuma', '見沼', 550, 70, 'Minuma or Minuma Rice Paddies is an area of paddy fields and other agricultural fields along the Minuma Irrigational Canal. The area encompasses 1260 hectares and straddles across five wards of the city of Saitama. Despite its close proximity to major urban areas such as Saitama-Shintoshin Station and Ōmiya Station, idyllic scenery consisting of paddy fields, farmlands, forests and rivers still remains.', 'minuma.jpg', 'https://ja.wikipedia.org/wiki/見沼'
UNION SELECT 'Ōmiya Bonsai Village', '盆栽村', 480, 73, 'Ōmiya Bonsai Village is the nickname for the bonsai nursery precinct in Saitama. The Bonsai Village nurses hundreds of thousands of bonsai trees (bonsai pots) in a site of about 330,000 square meters.
', 'Omiyabonsaivillage.JPG', 'https://ja.wikipedia.org/wiki/盆栽村'
UNION SELECT 'Railway Museum', '鉄道博物館', 1120, 96, 'The Railway Museum opened on 14 October 2007. It was built and is operated by the East Japan Railway Culture Foundation, a non-profit affiliate of the East Japan Railway Company. It consists of a 19,800 m² building on a site covering 42,500 m², with a display area 9,500 m² in size.', 'railwaymuseum.jpg', 'https://ja.wikipedia.org/wiki/鉄道博物館'
UNION SELECT 'Saitama Stadium 2002', '埼玉スタジアム2002', 1340, 155, 'Saitama Stadium 2002, often called Saitama Stadium or simply Saisuta, is a football stadium located in Saitama City. Currently J. League football club Urawa Red Diamonds use this stadium for home games. It is one of the largest "football only" stadiums in Asia.', 'saitamastadium2002.jpg', 'https://ja.wikipedia.org/wiki/埼玉スタジアム2002'
UNION SELECT 'Saitama Super Arena', 'さいたまスーパーアリーナ', 1630, 160, 'Saitama Super Arena is a multi-purpose indoor arena. Its spectator capacity is 37,000 at maximum settings. This main arena capacity is between 19,000-22,500 when events such as basketball, volleyball and mixed martial arts take place there. It is also the only Japanese arena equipped especially for American football. The arena features a gigantic moveable section of seating which can reduce capacity for smaller events and create a more intimate setting.', 'saitamasuperarena.jpg', 'https://ja.wikipedia.org/wiki/さいたまスーパーアリーナ'
),
(SELECT cityID FROM cities WHERE city = 'Saitama' AND country = 'Japan');


-- Insert constructions for Uwajima, Japan
INSERT OR IGNORE INTO objects (name, nameOrig, price, rounds, desc, image, link, cityid)
SELECT * FROM (
SELECT 'Taga-taisha', '多賀神社', 800, 85, 'Although Taga doesn''t get much press at the local tourist office, it''s probably the most unusual sight in town: the shrine is an ancient Shinto fertility shrine, full of phalluses of all shapes and sizes, including a mighty carved log that gets carried about on festival days. It''s located on the north side of the river, not far from the better known Warei Shrine.', 'taga-taisha.jpg', 'https://ja.wikipedia.org/wiki/多賀大社'
UNION SELECT 'Uwajima Castle', '宇和島城', 1840, 165, 'Uwajima Castle is a hirayamashiro (Japanese castle on a hill on a plain) in Uwajima. An alternate name for this castle is Tsurushima-jo. This castle is well known as one of the twelve Japanese castles to still have an original donjon built in the Edo Period.', 'uwajimacastle.JPG', 'https://ja.wikipedia.org/wiki/宇和島城'
UNION SELECT 'Warei Shrine', '和霊神社', 475, 50, 'A large, comparatively staid Shinto shrine, probably Uwajima''s best-known attraction among the Japanese. Not worth a detour, but you''ll be passing by on your way to the Taga Shrine anyway', 'wareishrine.JPG', 'https://ja.wikipedia.org/wiki/和霊神社'
),
(SELECT cityID FROM cities WHERE city = 'Uwajima' AND country = 'Japan');


-- Fix images
UPDATE objects SET image = 'myoryu-ji.jpg' WHERE name = 'Myōryū-ji' AND cityID = (SELECT cityID FROM cities WHERE city = 'Kanazawa' AND country = 'Japan');
UPDATE objects SET image = 'zojo-ji.JPG' WHERE name = 'Zōjō-ji' AND cityID = (SELECT cityID FROM cities WHERE city = 'Tokyo' AND country = 'Japan');